aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 137787521523.dkr.ecr.us-east-1.amazonaws.com

docker build -t configserver-repo .

docker tag configserver-repo:latest 137787521523.dkr.ecr.us-east-1.amazonaws.com/configserver-repo:latest

docker push 137787521523.dkr.ecr.us-east-1.amazonaws.com/configserver-repo:latest

