app:
  security:
    user: root
    pass: s3cr3t

server:
  port: 8888

spring:
  application:
    name: configserver
  security:
    user:
      name: root
      password: s3cr3t
  profiles:
    active: jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/configserver?currentSchema=configserver_dev
    username: configserver_dev
    password: configserver_dev
    driver-class-name: org.postgresql.Driver
    # Configuracion de HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  cloud:
    config:
      server:
        jdbc:
          enabled: true
          sql: SELECT "key", "value" FROM PROPERTIES WHERE "application"=? AND "profile"=? AND "label"=?
management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
