app:
  security:
    user: ${CONFIGSERVER_SERVER_SECURITY_USER:root}
    pass: ${CONFIGSERVER_SERVER_SECURITY_PASS:s3cr3t}

server:
  port: ${CONFIGSERVER_SERVER_PORT:8888}

spring:
  application:
    name: configserver
#  security:
#    user:
#      name: root
#      password: s3cr3t
  profiles:
    active: jdbc
  datasource:
    url: ${CONFIGSERVER_DB_URL:jdbc:postgresql://localhost:5432/configserver?currentSchema=configserver_dev}
    username: ${CONFIGSERVER_DB_USER:configserver_dev}
    password: ${CONFIGSERVER_DB_PASS:configserver_dev}
    driver-class-name: ${CONFIGSERVER_DB_DRIVER:org.postgresql.Driver}
    # Configuracion de HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  cloud:
    config:
      server:
        jdbc:
          enabled: true
          sql: SELECT "key", "value" FROM PROPERTIES WHERE "application"=? AND "profile"=? AND "label"=?
management:
  server:
    port: ${CONFIGSERVER_MANAGEMENT_PORT:9090}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
